.PHONY: setup test reproduce tables figures supplement clean check-integrity \
        generate run-lexon run-baselines evaluate help

PYTHON  ?= python
UV      := uv
LEX     := lexon

help:
	@echo ""
	@echo "LEXON-Bench — Makefile targets"
	@echo "==============================="
	@echo "  make setup           Install dependencies (uv)"
	@echo "  make test            Run pytest test suite"
	@echo "  make reproduce       Full reproduction pipeline (seed=42)"
	@echo "  make tables          Generate paper-ready tables (requires reproduce)"
	@echo "  make figures         Generate paper figures (requires reproduce)"
	@echo "  make supplement      Build supplementary ZIP"
	@echo "  make clean           Remove generated outputs"
	@echo "  make check-integrity Run benchmark integrity checks"
	@echo ""

# ---------------------------------------------------------------------------
setup:
	$(UV) sync
	@echo "✓ Dependencies installed"

# ---------------------------------------------------------------------------
test:
	$(UV) run pytest tests/ -v --tb=short

# ---------------------------------------------------------------------------
generate:
	$(UV) run $(LEX) generate-benchmark --config configs/experiment_synthetic.yaml

run-lexon: generate
	$(UV) run $(LEX) run \
		--input data/processed/benchmark_instances.jsonl \
		--output outputs/results/lexon_predictions.jsonl \
		--split test

run-baselines: generate
	$(UV) run $(LEX) run-baseline checklist --split test
	$(UV) run $(LEX) run-baseline ontology-only --split test
	$(UV) run $(LEX) run-baseline flat-rules --split test

evaluate: run-lexon run-baselines
	$(UV) run $(LEX) evaluate \
		--gold data/processed/gold_labels.jsonl \
		--pred outputs/results/lexon_predictions.jsonl \
		--system-name "LEXON (full)" \
		--split test
	$(UV) run $(LEX) evaluate \
		--gold data/processed/gold_labels.jsonl \
		--pred outputs/results/checklist_predictions.jsonl \
		--system-name "B1 Static checklist" --split test
	$(UV) run $(LEX) evaluate \
		--gold data/processed/gold_labels.jsonl \
		--pred outputs/results/ontology_predictions.jsonl \
		--system-name "B2 Ontology (no rules)" --split test
	$(UV) run $(LEX) evaluate \
		--gold data/processed/gold_labels.jsonl \
		--pred outputs/results/flat_rules_predictions.jsonl \
		--system-name "B3 Flat rules (no graph)" --split test

reproduce:
	$(UV) run python scripts/reproduce_paper_results.py

tables:
	@test -f outputs/results/metrics_synthetic.csv || \
		(echo "Run 'make reproduce' first" && exit 1)
	@echo "✓ Tables already generated by reproduce pipeline"

figures:
	@test -f outputs/figures/pipeline.png || \
		(echo "Run 'make reproduce' first" && exit 1)
	@echo "✓ Figures already generated by reproduce pipeline"

supplement:
	$(UV) run $(LEX) export-supplement \
		--output outputs/lexon_supplementary.zip
	@echo "✓ Supplementary ZIP: outputs/lexon_supplementary.zip"

check-integrity:
	$(UV) run $(LEX) check-integrity

clean:
	rm -rf outputs/results/* outputs/tables/* outputs/figures/* \
		outputs/reports/* outputs/audit/* \
		data/processed/*.jsonl data/splits/*.txt
	find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	find . -name "*.pyc" -delete 2>/dev/null || true
	@echo "✓ Outputs cleaned"
